# Generated by Django 5.0.4 on 2024-10-20 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0011_alter_sale_stock_date_alter_stocks_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 15, 20, 16, 577722)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 15, 20, 16, 577722)),
        ),
    ]
