# Generated by Django 5.0.4 on 2024-11-02 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0012_alter_sale_stock_date_alter_stocks_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 2, 16, 42, 56, 191453)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 2, 16, 42, 56, 191453)),
        ),
    ]
